In [1]:
#library installation
import pandas as pd
import numpy as np

In [2]:
#file reading
ds = pd.read_csv('/workspaces/MiniProject1_GUVI/Uber_Eats_data.csv')
ds.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [3]:
#droping unwanted columns
ds = ds.drop(columns = ['phone','rest_type','dish_liked','listed_in(type)','listed_in(city)'])
ds.head()

,name,online_order,book_table,rate,votes,location,cuisines,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,"North Indian, Mughlai, Chinese",800
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,"Chinese, North Indian, Thai",800
2,San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Mexican, Italian",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,"South Indian, North Indian",300
4,Grand Village,No,No,3.8/5,166,Basavanagudi,"North Indian, Rajasthani",600

In [4]:
ds.info()

<class 'pandas.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23193 non-null  str
 1   online_order                 23193 non-null  str
 2   book_table                   23193 non-null  str
 3   rate                         23193 non-null  str
 4   votes                        23193 non-null  int64
 5   location                     23193 non-null  str
 6   cuisines                     23193 non-null  str
 7   approx_cost(for two people)  23193 non-null  str
dtypes: int64(1), str(7)
memory usage: 2.9 MB

In [5]:
#data cleaning in name column
print(ds.name.isnull().sum())
ds.name = ds.name.str.lower().str.strip()

0

In [6]:
#data cleaning in online_order column
print(ds.online_order.isnull().sum())
ds.online_order = ds.online_order.str.lower().str.strip()

0

In [7]:
#data cleaning book_table
print(ds.book_table.isnull().sum())
ds.book_table = ds.book_table.str.lower().str.strip()

0

In [8]:
#data cleaning rate
ds.rate = ds.rate.str.strip()
ds['rate'] = ds['rate'].str.replace('/5', '', regex=False)
ds['rate'] = pd.to_numeric(ds['rate'], errors='coerce')

In [9]:
ds.info()

<class 'pandas.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23193 non-null  str
 1   online_order                 23193 non-null  str
 2   book_table                   23193 non-null  str
 3   rate                         23046 non-null  float64
 4   votes                        23193 non-null  int64
 5   location                     23193 non-null  str
 6   cuisines                     23193 non-null  str
 7   approx_cost(for two people)  23193 non-null  str
dtypes: float64(1), int64(1), str(6)
memory usage: 2.8 MB

In [10]:
#checking null values in rate column
ds.rate.isnull().sum()

np.int64(147)

In [11]:
#dropping null values in rate column
ds = ds.dropna(subset=['rate'])

In [12]:
ds.info()

<class 'pandas.DataFrame'>
Index: 23046 entries, 0 to 23192
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23046 non-null  str
 1   online_order                 23046 non-null  str
 2   book_table                   23046 non-null  str
 3   rate                         23046 non-null  float64
 4   votes                        23046 non-null  int64
 5   location                     23046 non-null  str
 6   cuisines                     23046 non-null  str
 7   approx_cost(for two people)  23046 non-null  str
dtypes: float64(1), int64(1), str(6)
memory usage: 3.0 MB

In [13]:
# lowercase and extra space removal in location column data
ds.location = ds.location.str.lower().str.strip()

In [14]:
# null value check in location column
ds.location.isnull().sum()

np.int64(0)

In [15]:
# lowercase and extra space removal in cuisines column data
ds.cuisines = ds.cuisines.str.lower().str.strip()

In [16]:
# null value check in cuisines column
ds.cuisines.isnull().sum()

np.int64(0)

In [17]:
#creation of cost_for_two columns and cilling data from approx_cost(for two people) column
ds['cost_for_two'] = ds['approx_cost(for two people)']

In [18]:
ds.info()

<class 'pandas.DataFrame'>
Index: 23046 entries, 0 to 23192
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23046 non-null  str
 1   online_order                 23046 non-null  str
 2   book_table                   23046 non-null  str
 3   rate                         23046 non-null  float64
 4   votes                        23046 non-null  int64
 5   location                     23046 non-null  str
 6   cuisines                     23046 non-null  str
 7   approx_cost(for two people)  23046 non-null  str
 8   cost_for_two                 23046 non-null  str
dtypes: float64(1), int64(1), str(7)
memory usage: 3.3 MB

In [19]:
#droping approx_cost(for two people) column
ds = ds.drop(columns = 'approx_cost(for two people)')

In [20]:
#removing the extra spaces and , replacement
ds['cost_for_two'] = ds['cost_for_two'].str.strip()
ds['cost_for_two'] = ds['cost_for_two'].str.replace(',', '')
ds['cost_for_two'] = pd.to_numeric(ds['cost_for_two'], errors='coerce')

In [21]:
# checking for null values
ds.cost_for_two.isnull().sum()

np.int64(0)

In [22]:
ds.info()

<class 'pandas.DataFrame'>
Index: 23046 entries, 0 to 23192
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          23046 non-null  str
 1   online_order  23046 non-null  str
 2   book_table    23046 non-null  str
 3   rate          23046 non-null  float64
 4   votes         23046 non-null  int64
 5   location      23046 non-null  str
 6   cuisines      23046 non-null  str
 7   cost_for_two  23046 non-null  int64
dtypes: float64(1), int64(2), str(5)
memory usage: 2.9 MB

In [23]:
#rating normalization
C = ds['rate'].mean()
m = ds['votes'].quantile(0.75)

ds['normalized_rating'] = ((ds['votes'] / (ds['votes'] + m)) * ds['rate'] +(m / (ds['votes'] + m)) * C)

In [24]:
ds.info()

<class 'pandas.DataFrame'>
Index: 23046 entries, 0 to 23192
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               23046 non-null  str
 1   online_order       23046 non-null  str
 2   book_table         23046 non-null  str
 3   rate               23046 non-null  float64
 4   votes              23046 non-null  int64
 5   location           23046 non-null  str
 6   cuisines           23046 non-null  str
 7   cost_for_two       23046 non-null  int64
 8   normalized_rating  23046 non-null  float64
dtypes: float64(2), int64(2), str(5)
memory usage: 3.1 MB

In [25]:
ds.duplicated().sum()

np.int64(12913)

In [26]:
ds.duplicated(subset=['name', 'location']).sum()

np.int64(18538)

In [27]:
duplicates = ds[ds.duplicated(subset=['name', 'location'], keep=False)]
duplicates

,name,online_order,book_table,rate,votes,location,cuisines,cost_for_two,normalized_rating
0,jalsa,yes,yes,4.1,775,banashankari,"north indian, mughlai, chinese",800,4.015366
1,spice elephant,yes,no,4.1,787,banashankari,"chinese, north indian, thai",800,4.016103
2,san churro cafe,yes,no,3.8,918,banashankari,"cafe, mexican, italian",800,3.840881
3,addhuri udupi bhojana,no,no,3.7,88,banashankari,"south indian, north indian",300,3.877894
4,grand village,no,no,3.8,166,basavanagudi,"north indian, rajasthani",600,3.881493
...,...,...,...,...,...,...,...,...,...
23188,izakaya gastro pub,yes,yes,3.8,128,whitefield,"north indian, continental, mediterranean",1200,3.885800
23189,m bar - bengaluru marriott hotel whitefield,no,no,3.9,77,whitefield,finger food,2000,3.903877
23190,keys cafe - keys hotel,no,no,2.8,161,whitefield,"chinese, continental, north indian",1200,3.667939
23191,bhagini,no,no,2.5,81,whitefield,"andhra, south indian, chinese, north indian",800,3.735104
23192,chime - sheraton grand bengaluru whitefield ho...,no,yes,4.3,236,"itpl main road, whitefield",finger food,2500,4.017279

In [28]:
# droping duplicates based on name and location
ds = ds.drop_duplicates(subset = ['name','location'])

In [29]:
ds.info()

<class 'pandas.DataFrame'>
Index: 4508 entries, 0 to 23163
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               4508 non-null   str
 1   online_order       4508 non-null   str
 2   book_table         4508 non-null   str
 3   rate               4508 non-null   float64
 4   votes              4508 non-null   int64
 5   location           4508 non-null   str
 6   cuisines           4508 non-null   str
 7   cost_for_two       4508 non-null   int64
 8   normalized_rating  4508 non-null   float64
dtypes: float64(2), int64(2), str(5)
memory usage: 614.3 KB

In [30]:
ds.to_csv('/workspaces/MiniProject1_GUVI/cleaned_uber_eats.csv', index=False)

In [53]:
%pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /usr/local/python/3.12.1/lib/python3.12/site-packages (9.6.0)
Note: you may need to restart the kernel to use updated packages.

In [32]:
import sqlite3

conn = sqlite3.connect('/workspaces/MiniProject1_GUVI/uber.db')

ds.to_sql('restaurants', conn, if_exists='replace', index=False)

print("Data saved to SQLite!")

Data saved to SQLite!

In [33]:
test = pd.read_sql("SELECT * FROM restaurants LIMIT 5", conn)
test

,name,online_order,book_table,rate,votes,location,cuisines,cost_for_two,normalized_rating
0,jalsa,yes,yes,4.1,775,banashankari,"north indian, mughlai, chinese",800,4.015366
1,spice elephant,yes,no,4.1,787,banashankari,"chinese, north indian, thai",800,4.016103
2,san churro cafe,yes,no,3.8,918,banashankari,"cafe, mexican, italian",800,3.840881
3,addhuri udupi bhojana,no,no,3.7,88,banashankari,"south indian, north indian",300,3.877894
4,grand village,no,no,3.8,166,basavanagudi,"north indian, rajasthani",600,3.881493

In [34]:
mycursor = conn.cursor()

In [35]:
mycursor.execute("SELECT name FROM sqlite_master WHERE type='table';")

for x in mycursor:
    print(x)

('restaurants',)

In [ ]:
%pip install tabulate

Requirement already satisfied: tabulate in /usr/local/python/3.12.1/lib/python3.12/site-packages (0.10.0)

In [37]:
from tabulate import tabulate

In [38]:
# location highest average rating
mycursor.execute("SELECT location, ROUND(AVG(normalized_rating),2) AS avg_rating FROM restaurants GROUP BY location ORDER BY avg_rating DESC;")
out = mycursor.fetchall()
print(tabulate(out,headers = [i[0] for i in mycursor.description], tablefmt = 'psql'))

+-------------------------------+--------------+
| location                      |   avg_rating |
|-------------------------------+--------------|
| lavelle road                  |         4.07 |
| koramangala 5th block         |         4.03 |
| st. marks road                |         4.01 |
| race course road              |         4.01 |
| church street                 |         4    |
| vasanth nagar                 |         3.99 |
| sadashiv nagar                |         3.99 |
| residency road                |         3.99 |
| koramangala 3rd block         |         3.99 |
| sankey road                   |         3.98 |
| koramangala 4th block         |         3.98 |
| indiranagar                   |         3.98 |
| richmond road                 |         3.97 |
| mg road                       |         3.97 |
| cunningham road               |         3.97 |
| ulsoor                        |         3.96 |
| malleshwaram                  |         3.96 |
| brigade road                  |         3.96 |
| seshadripuram                 |         3.95 |
| koramangala 7th block         |         3.95 |
| rajajinagar                   |         3.94 |
| koramangala 6th block         |         3.94 |
| koramangala 2nd block         |         3.94 |
| kalyan nagar                  |         3.94 |
| jayanagar                     |         3.94 |
| infantry road                 |         3.94 |
| city market                   |         3.94 |
| whitefield                    |         3.93 |
| hosur road                    |         3.93 |
| basavanagudi                  |         3.93 |
| thippasandra                  |         3.92 |
| sarjapur road                 |         3.92 |
| new bel road                  |         3.92 |
| majestic                      |         3.92 |
| koramangala 8th block         |         3.92 |
| koramangala                   |         3.92 |
| jp nagar                      |         3.92 |
| sanjay nagar                  |         3.91 |
| koramangala 1st block         |         3.91 |
| kammanahalli                  |         3.91 |
| hsr                           |         3.91 |
| hennur                        |         3.91 |
| hbr layout                    |         3.91 |
| frazer town                   |         3.91 |
| banashankari                  |         3.91 |
| yelahanka                     |         3.9  |
| vijay nagar                   |         3.9  |
| sahakara nagar                |         3.9  |
| old airport road              |         3.9  |
| marathahalli                  |         3.9  |
| magadi road                   |         3.9  |
| langford town                 |         3.9  |
| yeshwantpur                   |         3.89 |
| wilson garden                 |         3.89 |
| btm                           |         3.89 |
| basaveshwara nagar            |         3.89 |
| shivajinagar                  |         3.88 |
| shanti nagar                  |         3.88 |
| ejipura                       |         3.88 |
| domlur                        |         3.88 |
| rt nagar                      |         3.87 |
| kr puram                      |         3.87 |
| jalahalli                     |         3.87 |
| itpl main road, whitefield    |         3.87 |
| electronic city               |         3.87 |
| bellandur                     |         3.87 |
| bannerghatta road             |         3.87 |
| varthur main road, whitefield |         3.86 |
| old madras road               |         3.86 |
| nagawara                      |         3.86 |
| mysore road                   |         3.86 |
| kaggadasapura                 |         3.86 |
| jeevan bhima nagar            |         3.86 |
| cv raman nagar                |         3.86 |
| banaswadi                     |         3.86 |
| rajarajeshwari nagar          |         3.85 |
| commercial street             |         3.85 |
| brookefield                   |         3.85 |
| uttarahalli                   |         3.84 |
| kanakapura road               |         3.84 |
| kumaraswamy layout            |         3.83 |
| east bangalore                |         3.8  |
| south bangalore               |         3.79 |
| rammurthy nagar               |         3.79 |
| bommanahalli                  |         3.79 |
| central bangalore             |         3.78 |
| north bangalore               |         3.76 |
| west bangalore                |         3.62 |
+-------------------------------+--------------+

In [39]:
# saturated areas
mycursor.execute("SELECT location, COUNT(*) AS total_restaurants FROM restaurants GROUP BY location ORDER BY total_restaurants DESC;")
out = mycursor.fetchall()
print(tabulate(out,headers = [i[0] for i in mycursor.description], tablefmt = 'psql'))

+-------------------------------+---------------------+
| location                      |   total_restaurants |
|-------------------------------+---------------------|
| indiranagar                   |                 304 |
| whitefield                    |                 293 |
| hsr                           |                 269 |
| marathahalli                  |                 223 |
| jp nagar                      |                 187 |
| btm                           |                 187 |
| jayanagar                     |                 180 |
| koramangala 5th block         |                 171 |
| electronic city               |                 156 |
| bannerghatta road             |                 128 |
| kalyan nagar                  |                 120 |
| sarjapur road                 |                 115 |
| malleshwaram                  |                 113 |
| new bel road                  |                 111 |
| bellandur                     |                 106 |
| banashankari                  |                 100 |
| koramangala 7th block         |                  82 |
| koramangala 6th block         |                  82 |
| basavanagudi                  |                  80 |
| brookefield                   |                  75 |
| koramangala 4th block         |                  73 |
| frazer town                   |                  66 |
| kammanahalli                  |                  63 |
| mg road                       |                  58 |
| banaswadi                     |                  58 |
| old airport road              |                  57 |
| brigade road                  |                  56 |
| koramangala 1st block         |                  55 |
| rajajinagar                   |                  53 |
| residency road                |                  51 |
| ulsoor                        |                  50 |
| lavelle road                  |                  47 |
| church street                 |                  46 |
| jeevan bhima nagar            |                  45 |
| richmond road                 |                  39 |
| domlur                        |                  35 |
| nagawara                      |                  34 |
| basaveshwara nagar            |                  30 |
| st. marks road                |                  28 |
| cunningham road               |                  27 |
| kaggadasapura                 |                  25 |
| seshadripuram                 |                  24 |
| kumaraswamy layout            |                  23 |
| vasanth nagar                 |                  21 |
| itpl main road, whitefield    |                  21 |
| sahakara nagar                |                  20 |
| shanti nagar                  |                  19 |
| commercial street             |                  19 |
| race course road              |                  18 |
| thippasandra                  |                  16 |
| sadashiv nagar                |                  16 |
| rt nagar                      |                  15 |
| koramangala 8th block         |                  15 |
| majestic                      |                  14 |
| yeshwantpur                   |                  13 |
| sanjay nagar                  |                  13 |
| koramangala 3rd block         |                  13 |
| hennur                        |                  13 |
| vijay nagar                   |                  11 |
| hbr layout                    |                  10 |
| varthur main road, whitefield |                   9 |
| sankey road                   |                   9 |
| cv raman nagar                |                   9 |
| bommanahalli                  |                   9 |
| shivajinagar                  |                   8 |
| infantry road                 |                   8 |
| ejipura                       |                   7 |
| wilson garden                 |                   6 |
| south bangalore               |                   6 |
| old madras road               |                   5 |
| hosur road                    |                   5 |
| city market                   |                   5 |
| uttarahalli                   |                   3 |
| rammurthy nagar               |                   3 |
| koramangala 2nd block         |                   3 |
| koramangala                   |                   3 |
| east bangalore                |                   3 |
| rajarajeshwari nagar          |                   2 |
| mysore road                   |                   2 |
| kanakapura road               |                   2 |
| jalahalli                     |                   2 |
| yelahanka                     |                   1 |
| west bangalore                |                   1 |
| north bangalore               |                   1 |
| magadi road                   |                   1 |
| langford town                 |                   1 |
| kr puram                      |                   1 |
| central bangalore             |                   1 |
+-------------------------------+---------------------+

In [40]:
# rating based on online booking
mycursor.execute("SELECT online_order, ROUND(AVG(normalized_rating),2) AS avg_rating FROM restaurants GROUP BY online_order ORDER BY avg_rating DESC;")
out = mycursor.fetchall()
print(tabulate(out,headers = [i[0] for i in mycursor.description], tablefmt = 'psql'))

+----------------+--------------+
| online_order   |   avg_rating |
|----------------+--------------|
| no             |         3.96 |
| yes            |         3.91 |
+----------------+--------------+

In [41]:
mycursor.execute("SELECT book_table, ROUND(AVG(normalized_rating),2) AS avg_rating FROM restaurants GROUP BY book_table ORDER BY avg_rating DESC;")
out = mycursor.fetchall()
print(tabulate(out,headers = [i[0] for i in mycursor.description], tablefmt = 'psql'))

+--------------+--------------+
| book_table   |   avg_rating |
|--------------+--------------|
| yes          |         4.05 |
| no           |         3.89 |
+--------------+--------------+

In [42]:
#price category and rating insights
mycursor.execute("SELECT CASE WHEN cost_for_two < 500 THEN 'Low' WHEN cost_for_two BETWEEN 500 AND 1000 THEN 'Mid' ELSE 'High' END AS Price_category, ROUND(AVG(normalized_rating), 2) AS avg_rating FROM restaurants GROUP BY price_category ORDER BY avg_rating DESC")
out = mycursor.fetchall()
print(tabulate(out,headers = [i[0] for i in mycursor.description], tablefmt = 'psql'))

+------------------+--------------+
| Price_category   |   avg_rating |
|------------------+--------------|
| High             |         4.08 |
| Mid              |         3.91 |
| Low              |         3.89 |
+------------------+--------------+

In [43]:
mycursor.execute("SELECT cuisines, COUNT(*) AS total_restaurants FROM restaurants GROUP BY cuisines ORDER BY total_restaurants DESC;")
out = mycursor.fetchall()
print(tabulate(out,headers = [i[0] for i in mycursor.description], tablefmt = 'psql'))

+--------------------------------------------------------------------------------------+---------------------+
| cuisines                                                                             |   total_restaurants |
|--------------------------------------------------------------------------------------+---------------------|
| north indian                                                                         |                 239 |
| north indian, chinese                                                                |                 166 |
| south indian                                                                         |                 117 |
| ice cream, desserts                                                                  |                  59 |
| bakery, desserts                                                                     |                  59 |
| south indian, north indian, chinese                                                  |                  53 |
| pizza, fast food                                                                     |                  51 |
| cafe                                                                                 |                  49 |
| burger, fast food                                                                    |                  48 |
| desserts                                                                             |                  42 |
| biryani                                                                              |                  41 |
| pizza                                                                                |                  39 |
| mithai, street food                                                                  |                  39 |
| chinese                                                                              |                  37 |
| desserts, beverages                                                                  |                  36 |
| chinese, momos                                                                       |                  35 |
| fast food                                                                            |                  33 |
| north indian, chinese, biryani                                                       |                  29 |
| chinese, thai                                                                        |                  29 |
| south indian, north indian, chinese, street food                                     |                  26 |
| finger food                                                                          |                  25 |
| north indian, mughlai                                                                |                  24 |
| north indian, biryani, fast food                                                     |                  24 |
| bakery                                                                               |                  24 |
| north indian, south indian, chinese                                                  |                  21 |
| north indian, biryani                                                                |                  21 |
| desserts, ice cream                                                                  |                  21 |
| biryani, north indian                                                                |                  21 |
| north indian, street food                                                            |                  20 |
| cafe, fast food                                                                      |                  20 |
| biryani, north indian, chinese                                                       |                  20 |
| street food                                                                          |                  19 |
| chinese, thai, momos                                                                 |                  19 |
| burger, fast food, beverages                                                         |                  18 |
| beverages, fast food                                                                 |                  18 |
| andhra, biryani, north indian, chinese                                               |                  18 |
| north indian, south indian                                                           |                  17 |
| cafe, continental                                                                    |                  17 |
| biryani, kebab                                                                       |                  17 |
| north indian, mughlai, fast food                                                     |                  16 |
| continental                                                                          |                  16 |
| chinese, north indian                                                                |                  16 |
| arabian                                                                              |                  16 |
| pizza, italian                                                                       |                  15 |
| north indian, continental                                                            |                  15 |
| south indian, north indian, chinese, street food, fast food                          |                  14 |
| south indian, north indian                                                           |                  14 |
| north indian, mughlai, chinese                                                       |                  14 |
| fast food, rolls, momos                                                              |                  14 |
| desserts, bakery                                                                     |                  14 |
| andhra, biryani                                                                      |                  14 |
| tea, beverages, fast food                                                            |                  13 |
| salad, fast food                                                                     |                  13 |
| pizza, cafe, italian                                                                 |                  13 |
| north indian, mughlai, south indian, chinese                                         |                  13 |
| north indian, chinese, fast food                                                     |                  13 |
| north indian, chinese, continental                                                   |                  13 |
| mexican, italian                                                                     |                  13 |
| italian                                                                              |                  13 |
| kerala                                                                               |                  12 |
| italian, pizza                                                                       |                  12 |
| bengali                                                                              |                  12 |
| tibetan, momos                                                                       |                  11 |
| north indian, fast food, street food                                                 |                  11 |
| north indian, fast food                                                              |                  11 |
| mexican, fast food                                                                   |                  11 |
| ice cream, desserts, beverages, sandwich                                             |                  11 |
| healthy food, chinese, biryani, north indian, continental, salad, american, burger   |                  11 |
| fast food, burger                                                                    |                  11 |
| beverages, desserts                                                                  |                  11 |
| street food, north indian                                                            |                  10 |
| street food, fast food                                                               |                  10 |
| south indian, biryani                                                                |                  10 |
| fast food, rolls                                                                     |                  10 |
| cafe, desserts                                                                       |                  10 |
| biryani, andhra, north indian, chinese                                               |                  10 |
| beverages                                                                            |                  10 |
| bakery, fast food                                                                    |                  10 |
| andhra, north indian, chinese                                                        |                  10 |
| south indian, chinese                                                                |                   9 |
| north indian, european, mediterranean, bbq, kebab                                    |                   9 |
| north indian, chinese, seafood                                                       |                   9 |
| ice cream                                                                            |                   9 |
| desserts, beverages, ice cream                                                       |                   9 |
| cafe, italian                                                                        |                   9 |
| south indian, north indian, chinese, beverages                                       |                   8 |
| north indian, chinese, south indian                                                  |                   8 |
| north indian, chinese, rolls                                                         |                   8 |
| north indian, biryani, chinese                                                       |                   8 |
| fast food, beverages                                                                 |                   8 |
| desserts, fast food                                                                  |                   8 |
| continental, north indian, chinese                                                   |                   8 |
| continental, north indian                                                            |                   8 |
| chinese, thai, momos, vietnamese                                                     |                   8 |
| chinese, north indian, south indian                                                  |                   8 |
| street food, mithai                                                                  |                   7 |
| south indian, fast food                                                              |                   7 |
| south indian, chinese, north indian                                                  |                   7 |
| seafood, north indian, chinese                                                       |                   7 |
| north indian, continental, chinese                                                   |                   7 |
| north indian, chinese, mughlai                                                       |                   7 |
| mughlai, north indian, chinese                                                       |                   7 |
| modern indian                                                                        |                   7 |
| mangalorean, seafood                                                                 |                   7 |
| fast food, north indian                                                              |                   7 |
| chettinad, south indian                                                              |                   7 |
| cafe, burger, beverages                                                              |                   7 |
| cafe, beverages                                                                      |                   7 |
| biryani, north indian, mughlai                                                       |                   7 |
| biryani, north indian, kebab                                                         |                   7 |
| beverages, desserts, ice cream                                                       |                   7 |
| rajasthani                                                                           |                   6 |
| north indian, south indian, chinese, continental                                     |                   6 |
| north indian, mughlai, biryani                                                       |                   6 |
| north indian, continental, italian                                                   |                   6 |
| north indian, chinese, biryani, rolls                                                |                   6 |
| japanese                                                                             |                   6 |
| italian, salad                                                                       |                   6 |
| fast food, street food                                                               |                   6 |
| continental, chinese                                                                 |                   6 |
| continental, american                                                                |                   6 |
| chinese, south indian, north indian                                                  |                   6 |
| chinese, continental, north indian                                                   |                   6 |
| cafe, italian, burger, american, steak                                               |                   6 |
| cafe, continental, italian, burger                                                   |                   6 |
| cafe, continental, italian                                                           |                   6 |
| cafe, bakery                                                                         |                   6 |
| andhra, north indian                                                                 |                   6 |
| north indian, mughlai, biryani, rolls                                                |                   5 |
| north indian, chinese, street food                                                   |                   5 |
| north indian, chinese, biryani, seafood                                              |                   5 |
| north indian, chinese, andhra                                                        |                   5 |
| mexican, american, fast food                                                         |                   5 |
| mexican                                                                              |                   5 |
| maharashtrian                                                                        |                   5 |
| korean                                                                               |                   5 |
| kerala, seafood                                                                      |                   5 |
| juices, fast food                                                                    |                   5 |
| ice cream, beverages                                                                 |                   5 |
| healthy food, beverages                                                              |                   5 |
| european, mediterranean, north indian, bbq                                           |                   5 |
| desserts, ice cream, beverages, sandwich                                             |                   5 |
| desserts, ice cream, beverages                                                       |                   5 |
| chinese, tibetan, momos                                                              |                   5 |
| cafe, italian, continental                                                           |                   5 |
| cafe, continental, fast food                                                         |                   5 |
| cafe, continental, beverages                                                         |                   5 |
| cafe, american, burger, steak                                                        |                   5 |
| burger, turkish, arabian, fast food, salad, healthy food, desserts                   |                   5 |
| biryani, north indian, chinese, seafood                                              |                   5 |
| biryani, fast food                                                                   |                   5 |
| bengali, seafood                                                                     |                   5 |
| bengali, north indian, chinese                                                       |                   5 |
| andhra, north indian, chinese, biryani                                               |                   5 |
| andhra, north indian, biryani                                                        |                   5 |
| andhra, chinese, north indian                                                        |                   5 |
| andhra, biryani, north indian                                                        |                   5 |
| andhra                                                                               |                   5 |
| thai                                                                                 |                   4 |
| south indian, north indian, fast food                                                |                   4 |
| south indian, north indian, chinese, street food, juices                             |                   4 |
| south indian, north indian, chinese, biryani                                         |                   4 |
| south indian, biryani, chinese, north indian                                         |                   4 |
| south indian, beverages                                                              |                   4 |
| seafood, mangalorean                                                                 |                   4 |
| seafood, bbq, biryani                                                                |                   4 |
| rajasthani, north indian                                                             |                   4 |
| north indian, street food, mithai                                                    |                   4 |
| north indian, rolls                                                                  |                   4 |
| north indian, kebab, chinese, fast food                                              |                   4 |
| kerala, south indian                                                                 |                   4 |
| kerala, north indian, chinese                                                        |                   4 |
| ice cream, bakery, desserts                                                          |                   4 |
| finger food, continental                                                             |                   4 |
| fast food, sandwich                                                                  |                   4 |
| european, continental                                                                |                   4 |
| desserts, cafe                                                                       |                   4 |

In [44]:
mycursor.execute("SELECT cuisines,ROUND(AVG(normalized_rating),2) AS avg_rating FROM restaurants GROUP BY Cuisines ORDER BY avg_rating DESC;")
out = mycursor.fetchall()
print(tabulate(out,headers = [i[0] for i in mycursor.description], tablefmt = 'psql'))

+--------------------------------------------------------------------------------------+--------------+
| cuisines                                                                             |   avg_rating |
|--------------------------------------------------------------------------------------+--------------|
| continental, north indian, italian, south indian, finger food                        |         4.87 |
| north indian, european, mediterranean, bbq                                           |         4.73 |
| asian, chinese, thai, momos                                                          |         4.69 |
| asian, mediterranean, north indian, bbq                                              |         4.68 |
| italian, american, pizza                                                             |         4.67 |
| north indian, european, mediterranean                                                |         4.66 |
| american, continental, north indian, mediterranean                                   |         4.65 |
| continental, european, bbq, chinese, asian                                           |         4.64 |
| continental, asian, north indian                                                     |         4.64 |
| continental, north indian, bbq, steak                                                |         4.63 |
| american, tex-mex, burger, bbq, mexican                                              |         4.63 |
| north indian, thai, japanese, continental, cafe                                      |         4.61 |
| european, mediterranean, north indian, bbq                                           |         4.6  |
| continental, bbq, salad                                                              |         4.6  |
| chinese, american, continental, italian, north indian                                |         4.58 |
| cafe, american, burger                                                               |         4.55 |
| american, north indian, salad                                                        |         4.54 |
| asian, thai, vietnamese, malaysian, beverages                                        |         4.51 |
| european, italian, desserts, salad, juices, steak                                    |         4.5  |
| asian, burmese                                                                       |         4.48 |
| cafe, american, burger, steak                                                        |         4.47 |
| chinese, asian, cantonese, tea                                                       |         4.46 |
| cafe, pizza, beverages                                                               |         4.46 |
| american, continental, salad                                                         |         4.46 |
| american, continental, north indian, salad                                           |         4.46 |
| mediterranean, pizza, continental, seafood, salad                                    |         4.45 |
| american, north indian, chinese, finger food                                         |         4.45 |
| american, bbq                                                                        |         4.44 |
| pizza, north indian, modern indian                                                   |         4.42 |
| continental, asian, italian, north indian                                            |         4.42 |
| cafe, italian, fast food                                                             |         4.42 |
| north indian, mughlai, salad                                                         |         4.41 |
| north indian, mughlai, italian                                                       |         4.41 |
| north indian, chinese, continental, thai, salad                                      |         4.41 |
| cafe, american, burger, beverages                                                    |         4.41 |
| spanish, italian, mediterranean, european, salad                                     |         4.4  |
| north indian, continental, chinese, thai                                             |         4.4  |
| north indian, asian, seafood, chinese                                                |         4.4  |
| ice cream, cafe, beverages, burger, desserts, pizza                                  |         4.39 |
| continental, north indian, chinese, american, pizza, finger food                     |         4.39 |
| continental, mediterranean, italian, north indian, finger food, asian, momos         |         4.39 |
| steak, continental, burger, bbq                                                      |         4.37 |
| mediterranean, european, salad                                                       |         4.37 |
| european, continental                                                                |         4.37 |
| north indian, south indian, chinese, continental, mangalorean                        |         4.36 |
| continental, north indian, asian, italian                                            |         4.36 |
| continental, american, italian, modern indian, pizza, burger                         |         4.36 |
| seafood, goan, north indian, continental, asian                                      |         4.34 |
| north indian, european, mediterranean, bbq, kebab                                    |         4.34 |
| asian, north indian, thai                                                            |         4.34 |
| asian, burger, pizza, chinese, finger food                                           |         4.34 |
| parsi, north indian                                                                  |         4.33 |
| continental, mediterranean, north indian, chinese, finger food                       |         4.33 |
| chinese, thai, asian, malaysian, vietnamese, sri lankan, burmese                     |         4.33 |
| vietnamese, salad                                                                    |         4.32 |
| north indian, japanese                                                               |         4.32 |
| north indian, continental, cafe                                                      |         4.32 |
| continental, finger food, asian, north indian                                        |         4.32 |
| chinese, continental, north indian, mexican                                          |         4.32 |
| cafe, american, burger, sandwich, beverages                                          |         4.32 |
| american, tex-mex, burger, bbq                                                       |         4.32 |
| pizza, cafe, italian                                                                 |         4.31 |
| north indian, mughlai, biryani, south indian, beverages                              |         4.31 |
| asian, thai, chinese, bbq, momos                                                     |         4.31 |
| north indian, mediterranean, european, bbq                                           |         4.3  |
| continental, north indian, pizza, italian                                            |         4.3  |
| continental, north indian, chinese, european, bbq, finger food, asian                |         4.3  |
| chinese, continental, north indian, finger food                                      |         4.3  |
| american, south indian, thai, pizza, italian                                         |         4.3  |
| american, continental, steak                                                         |         4.3  |
| north indian, chinese, continental, mexican                                          |         4.29 |
| healthy food, mediterranean, desserts, italian, pizza, salad, kebab                  |         4.29 |
| continental, north indian, chinese, pizza, thai                                      |         4.29 |
| continental, mediterranean, south indian, north indian, asian                        |         4.29 |
| italian, pizza, beverages                                                            |         4.28 |
| finger food, continental, north indian                                               |         4.28 |
| bbq, north indian, continental, chinese                                              |         4.28 |
| north indian, italian                                                                |         4.27 |
| modern indian, european, asian                                                       |         4.26 |
| continental, italian, north indian, mexican                                          |         4.26 |
| continental, finger food, asian, chinese                                             |         4.26 |
| biryani, seafood, andhra, north indian                                               |         4.26 |
| bbq                                                                                  |         4.26 |
| middle eastern, fast food, rolls                                                     |         4.25 |
| malaysian, thai, singaporean, asian, chinese, momos                                  |         4.25 |
| italian, pizza, salad                                                                |         4.25 |
| finger food, continental, seafood                                                    |         4.25 |
| continental, salad, burger, finger food, pizza                                       |         4.25 |
| asian, japanese, vietnamese, korean, chinese, thai                                   |         4.25 |
| american, asian, european, north indian                                              |         4.25 |
| vietnamese, thai, burmese, japanese                                                  |         4.24 |
| street food, desserts, north indian, mithai, rajasthani                              |         4.24 |
| north indian, chinese, mughlai, mexican, bbq                                         |         4.24 |
| korean, chinese, japanese                                                            |         4.24 |
| continental, mexican, chinese, north indian                                          |         4.24 |
| continental, american, asian, north indian, burger                                   |         4.24 |
| asian, continental, european, north indian, mediterranean                            |         4.24 |
| american, north indian, pizza, finger food, continental, italian                     |         4.24 |
| north indian, chinese, continental, momos                                            |         4.23 |
| mangalorean, seafood, south indian, north indian, chinese, mughlai                   |         4.23 |
| continental, bbq, finger food                                                        |         4.23 |
| american, cafe, continental, french, burger, mexican, desserts, pizza                |         4.23 |
| mangalorean, konkan, seafood, kerala                                                 |         4.22 |
| continental, finger food, north indian, chinese                                      |         4.22 |
| chinese, sushi, asian, thai                                                          |         4.22 |
| biryani, andhra, north indian, seafood                                               |         4.22 |
| asian, japanese, korean, indonesian, malaysian, singaporean                          |         4.22 |
| african, burger                                                                      |         4.22 |
| steak, italian, continental, american, burger, bbq, salad                            |         4.21 |
| modern indian, european, american                                                    |         4.21 |
| cafe, european, continental                                                          |         4.21 |
| modern indian                                                                        |         4.2  |
| healthy food, salad, mediterranean                                                   |         4.2  |
| continental, mediterranean, european                                                 |         4.2  |
| continental, cafe, italian, fast food, steak                                         |         4.2  |
| cafe, continental, italian, german, french, spanish                                  |         4.2  |
| asian, thai                                                                          |         4.2  |
| asian, japanese, thai                                                                |         4.2  |
| malaysian, singaporean, thai                                                         |         4.19 |
| ice cream, cafe, pizza, burger, desserts, beverages                                  |         4.19 |
| european, mediterranean, asian, north indian, south indian, momos                    |         4.19 |
| continental, mexican, burger, desserts, italian, pizza, north indian, chinese        |         4.19 |
| continental, finger food, pizza                                                      |         4.19 |
| continental, fast food, european                                                     |         4.19 |
| cafe, continental, mediterranean, beverages                                          |         4.19 |
| cafe, burger, pizza, sandwich                                                        |         4.19 |
| asian, malaysian, chinese, thai, momos                                               |         4.19 |
| steak, continental, burger, american, bbq, european, salad                           |         4.18 |
| north indian, continental, chettinad, andhra, bengali                                |         4.18 |
| north indian, chinese, japanese, european, seafood                                   |         4.18 |
| finger food, north indian, continental                                               |         4.18 |
| desserts, cafe, beverages                                                            |         4.18 |
| arabian, north indian, beverages                                                     |         4.18 |
| portuguese, african                                                                  |         4.17 |
| pizza, italian, chinese, thai                                                        |         4.17 |
| healthy food, cafe, beverages                                                        |         4.17 |
| continental, north indian, chinese, salad                                            |         4.17 |
| cafe, continental, beverages, burger, desserts, pizza, bakery, european              |         4.17 |
| american, north indian, chinese, finger food, momos                                  |         4.17 |
| american, cafe, continental                                                          |         4.17 |
| turkish, arabian, fast food, desserts, healthy food, salad                           |         4.16 |
| north indian, mughlai, lucknowi                                                      |         4.16 |
| italian, salad, mediterranean                                                        |         4.16 |
| italian, continental, pizza                                                          |         4.16 |
| finger food, continental, north indian, italian, japanese                            |         4.16 |
| desserts, asian, beverages                                                           |         4.16 |
| cafe, fast food, burger                                                              |         4.16 |
| cafe, desserts, continental                                                          |         4.16 |
| cafe, continental, pizza, salad                                                      |         4.16 |
| bakery, cafe, italian, desserts                                                      |         4.16 |
| russian, continental, north indian                                                   |         4.15 |
| north indian, south indian, andhra, chinese                                          |         4.15 |
| italian, salad, healthy food, cafe, asian, desserts, pizza                           |         4.15 |
| italian, pizza, mexican                                                              |         4.15 |
| italian, american, steak, continental, bbq, salad                                    |         4.15 |
| italian                                                                              |         4.15 |
| french, sandwich, salad                                                              |         4.15 |
| continental, north indian, beverages                                                 |         4.15 |
| chettinad, andhra, kerala                                                            |         4.15 |
| asian, european, italian, korean, malaysian, thai, vietnamese, chinese               |         4.15 |
| asian, chinese, continental, north indian, south indian                              |         4.15 |
| seafood, continental, north indian, south indian                                     |         4.14 |
| pizza, biryani, north indian, south indian                                           |         4.14 |
| north indian, arabian, mughlai, biryani, seafood, beverages                          |         4.14 |
| italian, salad                                                                       |         4.14 |
| european, north indian, mediterranean, asian, salad                                  |         4.14 |
| european, continental, asian, finger food                                            |         4.14 |
| european, american                                                                   |         4.14 |
| chinese, continental, finger food, italian                                           |         4.14 |
| cafe, italian, continental, burger                                                   |         4.14 |
| american, continental, bbq, steak                                                    |         4.14 |
| american, chinese, continental, north indian                                         |         4.14 |
| sushi, japanese, chinese, thai                                                       |         4.13 |
| north indian, seafood                                                                |         4.13 |
| north indian, chinese, street food, juices                                           |         4.13 |
| continental, north indian, japanese, italian                                         |         4.13 |
| continental, north indian, finger food                                               |         4.13 |
| continental, italian, north indian                                                   |         4.13 |
| continental, italian, mexican, asian                                                 |         4.13 |
| continental, cafe, desserts, salad, momos                                            |         4.13 |
| cafe, healthy food, salad, continental, beverages, italian, sandwich                 |         4.13 |
| cafe, continental, sandwich, beverages                                               |         4.13 |
| biryani, chinese, north indian, seafood                                              |         4.13 |
| bbq, chinese, japanese, asian                                                        |         4.13 |
| arabian, biryani, chinese, middle eastern, fast food, north indian, mughlai, seafood |         4.13 |
| american, finger food, bbq, steak                                                    |         4.13 |
| thai, chinese, indonesian, asian, momos                                              |         4.12 |
| north indian, chinese, italian, street food, desserts                                |         4.12 |
| kerala, seafood, chinese, biryani, juices                                            |         4.12 |

In [45]:
mycursor.execute("SELECT cuisines, Count(*) AS total_restaurants, ROUND(AVG(normalized_rating),2) AS avg_rating FROM restaurants GROUP BY cuisines HAVING total_restaurants < 50 ORDER BY avg_rating DESC;")
out=mycursor.fetchall()
print(tabulate(out,headers = [i[0] for i in mycursor.description], tablefmt = 'psql'))

+--------------------------------------------------------------------------------------+---------------------+--------------+
| cuisines                                                                             |   total_restaurants |   avg_rating |
|--------------------------------------------------------------------------------------+---------------------+--------------|
| continental, north indian, italian, south indian, finger food                        |                   1 |         4.87 |
| north indian, european, mediterranean, bbq                                           |                   1 |         4.73 |
| asian, chinese, thai, momos                                                          |                   1 |         4.69 |
| asian, mediterranean, north indian, bbq                                              |                   2 |         4.68 |
| italian, american, pizza                                                             |                   1 |         4.67 |
| north indian, european, mediterranean                                                |                   1 |         4.66 |
| american, continental, north indian, mediterranean                                   |                   1 |         4.65 |
| continental, european, bbq, chinese, asian                                           |                   1 |         4.64 |
| continental, asian, north indian                                                     |                   2 |         4.64 |
| continental, north indian, bbq, steak                                                |                   1 |         4.63 |
| american, tex-mex, burger, bbq, mexican                                              |                   2 |         4.63 |
| north indian, thai, japanese, continental, cafe                                      |                   1 |         4.61 |
| european, mediterranean, north indian, bbq                                           |                   5 |         4.6  |
| continental, bbq, salad                                                              |                   1 |         4.6  |
| chinese, american, continental, italian, north indian                                |                   1 |         4.58 |
| cafe, american, burger                                                               |                   1 |         4.55 |
| american, north indian, salad                                                        |                   1 |         4.54 |
| asian, thai, vietnamese, malaysian, beverages                                        |                   1 |         4.51 |
| european, italian, desserts, salad, juices, steak                                    |                   2 |         4.5  |
| asian, burmese                                                                       |                   1 |         4.48 |
| cafe, american, burger, steak                                                        |                   5 |         4.47 |
| chinese, asian, cantonese, tea                                                       |                   1 |         4.46 |
| cafe, pizza, beverages                                                               |                   1 |         4.46 |
| american, continental, salad                                                         |                   1 |         4.46 |
| american, continental, north indian, salad                                           |                   1 |         4.46 |
| mediterranean, pizza, continental, seafood, salad                                    |                   1 |         4.45 |
| american, north indian, chinese, finger food                                         |                   2 |         4.45 |
| american, bbq                                                                        |                   1 |         4.44 |
| pizza, north indian, modern indian                                                   |                   1 |         4.42 |
| continental, asian, italian, north indian                                            |                   3 |         4.42 |
| cafe, italian, fast food                                                             |                   1 |         4.42 |
| north indian, mughlai, salad                                                         |                   1 |         4.41 |
| north indian, mughlai, italian                                                       |                   1 |         4.41 |
| north indian, chinese, continental, thai, salad                                      |                   1 |         4.41 |
| cafe, american, burger, beverages                                                    |                   1 |         4.41 |
| spanish, italian, mediterranean, european, salad                                     |                   1 |         4.4  |
| north indian, continental, chinese, thai                                             |                   1 |         4.4  |
| north indian, asian, seafood, chinese                                                |                   1 |         4.4  |
| ice cream, cafe, beverages, burger, desserts, pizza                                  |                   1 |         4.39 |
| continental, north indian, chinese, american, pizza, finger food                     |                   1 |         4.39 |
| continental, mediterranean, italian, north indian, finger food, asian, momos         |                   1 |         4.39 |
| steak, continental, burger, bbq                                                      |                   1 |         4.37 |
| mediterranean, european, salad                                                       |                   1 |         4.37 |
| european, continental                                                                |                   4 |         4.37 |
| north indian, south indian, chinese, continental, mangalorean                        |                   1 |         4.36 |
| continental, north indian, asian, italian                                            |                   2 |         4.36 |
| continental, american, italian, modern indian, pizza, burger                         |                   1 |         4.36 |
| seafood, goan, north indian, continental, asian                                      |                   1 |         4.34 |
| north indian, european, mediterranean, bbq, kebab                                    |                   9 |         4.34 |
| asian, north indian, thai                                                            |                   1 |         4.34 |
| asian, burger, pizza, chinese, finger food                                           |                   1 |         4.34 |
| parsi, north indian                                                                  |                   1 |         4.33 |
| continental, mediterranean, north indian, chinese, finger food                       |                   1 |         4.33 |
| chinese, thai, asian, malaysian, vietnamese, sri lankan, burmese                     |                   1 |         4.33 |
| vietnamese, salad                                                                    |                   1 |         4.32 |
| north indian, japanese                                                               |                   1 |         4.32 |
| north indian, continental, cafe                                                      |                   1 |         4.32 |
| continental, finger food, asian, north indian                                        |                   1 |         4.32 |
| chinese, continental, north indian, mexican                                          |                   1 |         4.32 |
| cafe, american, burger, sandwich, beverages                                          |                   1 |         4.32 |
| american, tex-mex, burger, bbq                                                       |                   1 |         4.32 |
| pizza, cafe, italian                                                                 |                  13 |         4.31 |
| north indian, mughlai, biryani, south indian, beverages                              |                   1 |         4.31 |
| asian, thai, chinese, bbq, momos                                                     |                   1 |         4.31 |
| north indian, mediterranean, european, bbq                                           |                   2 |         4.3  |
| continental, north indian, pizza, italian                                            |                   1 |         4.3  |
| continental, north indian, chinese, european, bbq, finger food, asian                |                   1 |         4.3  |
| chinese, continental, north indian, finger food                                      |                   1 |         4.3  |
| american, south indian, thai, pizza, italian                                         |                   1 |         4.3  |
| american, continental, steak                                                         |                   1 |         4.3  |
| north indian, chinese, continental, mexican                                          |                   1 |         4.29 |
| healthy food, mediterranean, desserts, italian, pizza, salad, kebab                  |                   1 |         4.29 |
| continental, north indian, chinese, pizza, thai                                      |                   1 |         4.29 |
| continental, mediterranean, south indian, north indian, asian                        |                   1 |         4.29 |
| italian, pizza, beverages                                                            |                   2 |         4.28 |
| finger food, continental, north indian                                               |                   2 |         4.28 |
| bbq, north indian, continental, chinese                                              |                   1 |         4.28 |
| north indian, italian                                                                |                   2 |         4.27 |
| modern indian, european, asian                                                       |                   1 |         4.26 |
| continental, italian, north indian, mexican                                          |                   1 |         4.26 |
| continental, finger food, asian, chinese                                             |                   1 |         4.26 |
| biryani, seafood, andhra, north indian                                               |                   2 |         4.26 |
| bbq                                                                                  |                   2 |         4.26 |
| middle eastern, fast food, rolls                                                     |                   1 |         4.25 |
| malaysian, thai, singaporean, asian, chinese, momos                                  |                   2 |         4.25 |
| italian, pizza, salad                                                                |                   3 |         4.25 |
| finger food, continental, seafood                                                    |                   1 |         4.25 |
| continental, salad, burger, finger food, pizza                                       |                   1 |         4.25 |
| asian, japanese, vietnamese, korean, chinese, thai                                   |                   1 |         4.25 |
| american, asian, european, north indian                                              |                   1 |         4.25 |
| vietnamese, thai, burmese, japanese                                                  |                   1 |         4.24 |
| street food, desserts, north indian, mithai, rajasthani                              |                   1 |         4.24 |
| north indian, chinese, mughlai, mexican, bbq                                         |                   1 |         4.24 |
| korean, chinese, japanese                                                            |                   1 |         4.24 |
| continental, mexican, chinese, north indian                                          |                   1 |         4.24 |
| continental, american, asian, north indian, burger                                   |                   1 |         4.24 |
| asian, continental, european, north indian, mediterranean                            |                   1 |         4.24 |
| american, north indian, pizza, finger food, continental, italian                     |                   1 |         4.24 |
| north indian, chinese, continental, momos                                            |                   1 |         4.23 |
| mangalorean, seafood, south indian, north indian, chinese, mughlai                   |                   1 |         4.23 |
| continental, bbq, finger food                                                        |                   2 |         4.23 |
| american, cafe, continental, french, burger, mexican, desserts, pizza                |                   1 |         4.23 |
| mangalorean, konkan, seafood, kerala                                                 |                   1 |         4.22 |
| continental, finger food, north indian, chinese                                      |                   4 |         4.22 |
| chinese, sushi, asian, thai                                                          |                   1 |         4.22 |
| biryani, andhra, north indian, seafood                                               |                   1 |         4.22 |
| asian, japanese, korean, indonesian, malaysian, singaporean                          |                   2 |         4.22 |
| african, burger                                                                      |                   2 |         4.22 |
| steak, italian, continental, american, burger, bbq, salad                            |                   1 |         4.21 |
| modern indian, european, american                                                    |                   1 |         4.21 |
| cafe, european, continental                                                          |                   1 |         4.21 |
| modern indian                                                                        |                   7 |         4.2  |
| healthy food, salad, mediterranean                                                   |                   1 |         4.2  |
| continental, mediterranean, european                                                 |                   1 |         4.2  |
| continental, cafe, italian, fast food, steak                                         |                   1 |         4.2  |
| cafe, continental, italian, german, french, spanish                                  |                   1 |         4.2  |
| asian, thai                                                                          |                   1 |         4.2  |
| asian, japanese, thai                                                                |                   2 |         4.2  |
| malaysian, singaporean, thai                                                         |                   1 |         4.19 |
| ice cream, cafe, pizza, burger, desserts, beverages                                  |                   3 |         4.19 |
| european, mediterranean, asian, north indian, south indian, momos                    |                   1 |         4.19 |
| continental, mexican, burger, desserts, italian, pizza, north indian, chinese        |                   1 |         4.19 |
| continental, finger food, pizza                                                      |                   1 |         4.19 |
| continental, fast food, european                                                     |                   1 |         4.19 |
| cafe, continental, mediterranean, beverages                                          |                   1 |         4.19 |
| cafe, burger, pizza, sandwich                                                        |                   1 |         4.19 |
| asian, malaysian, chinese, thai, momos                                               |                   1 |         4.19 |
| steak, continental, burger, american, bbq, european, salad                           |                   1 |         4.18 |
| north indian, continental, chettinad, andhra, bengali                                |                   1 |         4.18 |
| north indian, chinese, japanese, european, seafood                                   |                   1 |         4.18 |
| finger food, north indian, continental                                               |                   2 |         4.18 |
| desserts, cafe, beverages                                                            |                   2 |         4.18 |
| arabian, north indian, beverages                                                     |                   2 |         4.18 |
| portuguese, african                                                                  |                   1 |         4.17 |
| pizza, italian, chinese, thai                                                        |                   1 |         4.17 |
| healthy food, cafe, beverages                                                        |                   1 |         4.17 |
| continental, north indian, chinese, salad                                            |                   1 |         4.17 |
| cafe, continental, beverages, burger, desserts, pizza, bakery, european              |                   1 |         4.17 |
| american, north indian, chinese, finger food, momos                                  |                   2 |         4.17 |
| american, cafe, continental                                                          |                   3 |         4.17 |
| turkish, arabian, fast food, desserts, healthy food, salad                           |                   1 |         4.16 |
| north indian, mughlai, lucknowi                                                      |                   1 |         4.16 |
| italian, salad, mediterranean                                                        |                   1 |         4.16 |
| italian, continental, pizza                                                          |                   1 |         4.16 |
| finger food, continental, north indian, italian, japanese                            |                   1 |         4.16 |
| desserts, asian, beverages                                                           |                   1 |         4.16 |
| cafe, fast food, burger                                                              |                   1 |         4.16 |
| cafe, desserts, continental                                                          |                   2 |         4.16 |
| cafe, continental, pizza, salad                                                      |                   2 |         4.16 |
| bakery, cafe, italian, desserts                                                      |                   3 |         4.16 |
| russian, continental, north indian                                                   |                   1 |         4.15 |
| north indian, south indian, andhra, chinese                                          |                   1 |         4.15 |
| italian, salad, healthy food, cafe, asian, desserts, pizza                           |                   1 |         4.15 |
| italian, pizza, mexican                                                              |                   2 |         4.15 |
| italian, american, steak, continental, bbq, salad                                    |                   1 |         4.15 |

In [46]:
mycursor.execute("SELECT cost_for_two, ROUND((normalized_rating),2) AS avg_rating, COUNT(*) total_restaurants FROM restaurants GROUP BY cost_for_two ORDER BY cost_for_two;")
out = mycursor.fetchall()
print(tabulate(out,headers = [i[0] for i in mycursor.description], tablefmt = 'psql'))

+----------------+--------------+---------------------+
|   cost_for_two |   avg_rating |   total_restaurants |
|----------------+--------------+---------------------|
|             40 |         3.87 |                   3 |
|            100 |         4.03 |                  40 |
|            120 |         3.98 |                   1 |
|            150 |         4    |                  98 |
|            180 |         4.04 |                   2 |
|            200 |         3.89 |                 205 |
|            230 |         3.92 |                   1 |
|            250 |         3.89 |                 161 |
|            300 |         3.88 |                 357 |
|            330 |         3.83 |                   1 |
|            350 |         3.9  |                 118 |
|            400 |         3.82 |                 602 |
|            450 |         3.94 |                 168 |
|            500 |         3.98 |                 503 |
|            550 |         4.04 |                  91 |
|            600 |         3.88 |                 415 |
|            650 |         3.89 |                 126 |
|            700 |         3.94 |                 200 |
|            750 |         3.9  |                 138 |
|            800 |         4.02 |                 297 |
|            850 |         3.8  |                  33 |
|            900 |         3.85 |                  80 |
|            950 |         3.77 |                   8 |
|           1000 |         3.9  |                 171 |
|           1050 |         3.51 |                   1 |
|           1100 |         3.44 |                  65 |
|           1200 |         4.02 |                 125 |
|           1250 |         4.07 |                   4 |
|           1300 |         4.16 |                  57 |
|           1350 |         3.88 |                   2 |
|           1400 |         4.34 |                  63 |
|           1450 |         4.03 |                   1 |
|           1500 |         4.06 |                 123 |
|           1600 |         4.59 |                  35 |
|           1650 |         4.16 |                   1 |
|           1700 |         3.9  |                  31 |
|           1800 |         4.06 |                  28 |
|           1900 |         3.9  |                   7 |
|           2000 |         4    |                  46 |
|           2100 |         3.98 |                   6 |
|           2200 |         3.88 |                   9 |
|           2300 |         3.97 |                   1 |
|           2400 |         3.92 |                   4 |
|           2500 |         4.13 |                  27 |
|           2600 |         4.08 |                   1 |
|           2700 |         4.24 |                   1 |
|           2800 |         3.98 |                   3 |
|           3000 |         4.34 |                  28 |
|           3200 |         4.13 |                   1 |
|           3400 |         4.11 |                   2 |
|           3500 |         4.22 |                   5 |
|           3700 |         3.92 |                   1 |
|           4000 |         4.2  |                   7 |
|           4100 |         3.97 |                   1 |
|           4500 |         3.94 |                   1 |
|           5000 |         4.07 |                   1 |
|           6000 |         3.97 |                   1 |
+----------------+--------------+---------------------+

In [47]:
mycursor.execute("SELECT location, COUNT(*) AS total_premium_restaurants, ROUND(AVG(normalized_rating), 2) AS avg_rating FROM restaurants WHERE cost_for_two > 1000 GROUP BY location HAVING total_premium_restaurants >= 5 ORDER BY avg_rating DESC;")
out=mycursor.fetchall()
print(tabulate(out,headers = [i[0] for i in mycursor.description], tablefmt = 'psql'))

+-----------------------+-----------------------------+--------------+
| location              |   total_premium_restaurants |   avg_rating |
|-----------------------+-----------------------------+--------------|
| koramangala 7th block |                           8 |         4.24 |
| koramangala 5th block |                          30 |         4.22 |
| btm                   |                           6 |         4.2  |
| marathahalli          |                          34 |         4.18 |
| sarjapur road         |                          21 |         4.17 |
| st. marks road        |                           7 |         4.16 |
| rajajinagar           |                           6 |         4.13 |
| lavelle road          |                          31 |         4.13 |
| bannerghatta road     |                           5 |         4.13 |
| malleshwaram          |                          22 |         4.12 |
| indiranagar           |                          71 |         4.12 |
| jp nagar              |                          21 |         4.1  |
| koramangala 4th block |                          15 |         4.09 |
| cunningham road       |                           8 |         4.09 |
| residency road        |                          14 |         4.08 |
| church street         |                          13 |         4.08 |
| mg road               |                          32 |         4.07 |
| kalyan nagar          |                          19 |         4.07 |
| hsr                   |                          16 |         4.07 |
| whitefield            |                          74 |         4.06 |
| sadashiv nagar        |                           6 |         4.05 |
| race course road      |                           9 |         4.05 |
| new bel road          |                          10 |         4.05 |
| vasanth nagar         |                          11 |         4.03 |
| richmond road         |                          16 |         4.03 |
| brigade road          |                          16 |         4.03 |
| bellandur             |                          16 |         4.03 |
| old airport road      |                          14 |         4.01 |
| jayanagar             |                          13 |         4.01 |
| ulsoor                |                          17 |         4    |
| sankey road           |                           8 |         3.99 |
| koramangala 6th block |                          10 |         3.97 |
| electronic city       |                          24 |         3.97 |
| domlur                |                          12 |         3.97 |
| seshadripuram         |                           7 |         3.94 |
+-----------------------+-----------------------------+--------------+

In [48]:
mycursor.execute("SELECT location, COUNT (*) AS total_restaurants, ROUND(AVG(normalized_rating),2) AS avg_rating FROM restaurants GROUP BY location HAVING COUNT(*) > 50 AND AVG(normalized_rating) < 3.8 ORDER BY total_restaurants DESC;")
out = mycursor.fetchall()
print(tabulate(out,headers = [i[0] for i in mycursor.description], tablefmt = 'psql'))

+------------+---------------------+--------------+
| location   | total_restaurants   | avg_rating   |
|------------+---------------------+--------------|
+------------+---------------------+--------------+

In [49]:
mycursor.execute("SELECT online_order,book_table, COUNT(*) AS total_restaurants, ROUND(AVG(normalized_rating),2) AS avg_rating FROM restaurants GROUP BY online_order,book_table ORDER BY avg_rating DESC; ")
out = mycursor.fetchall()
print(tabulate(out,headers = [i[0] for i in mycursor.description], tablefmt = 'psql'))

+----------------+--------------+---------------------+--------------+
| online_order   | book_table   |   total_restaurants |   avg_rating |
|----------------+--------------+---------------------+--------------|
| no             | yes          |                 423 |         4.07 |
| yes            | yes          |                 465 |         4.04 |
| no             | no           |                1000 |         3.91 |
| yes            | no           |                2620 |         3.89 |
+----------------+--------------+---------------------+--------------+

In [50]:
query = """
SELECT 
    location,

    CASE 
        WHEN cost_for_two < 500 THEN 'Low'
        WHEN cost_for_two BETWEEN 500 AND 1000 THEN 'Mid'
        ELSE 'High'
    END AS price_category,

    COUNT(*) AS total_restaurants,
    ROUND(AVG(normalized_rating), 2) AS avg_rating

FROM restaurants

GROUP BY location, price_category

HAVING COUNT(*) >= 5

ORDER BY avg_rating DESC
LIMIT 10;
"""
mycursor.execute(query)
out = mycursor.fetchall()
print(tabulate(out, headers=[i[0] for i in mycursor.description], tablefmt='psql'))

+-----------------------+------------------+---------------------+--------------+
| location              | price_category   |   total_restaurants |   avg_rating |
|-----------------------+------------------+---------------------+--------------|
| koramangala 7th block | High             |                   8 |         4.24 |
| koramangala 5th block | High             |                  30 |         4.22 |
| btm                   | High             |                   6 |         4.2  |
| marathahalli          | High             |                  34 |         4.18 |
| sarjapur road         | High             |                  21 |         4.17 |
| st. marks road        | High             |                   7 |         4.16 |
| bannerghatta road     | High             |                   5 |         4.13 |
| lavelle road          | High             |                  31 |         4.13 |
| rajajinagar           | High             |                   6 |         4.13 |
| indiranagar           | High             |                  71 |         4.12 |
+-----------------------+------------------+---------------------+--------------+

In [51]:
query = """
SELECT 
    name,
    location,
    normalized_rating,

    CASE 
        WHEN cost_for_two < 500 THEN 'Low'
        WHEN cost_for_two BETWEEN 500 AND 1000 THEN 'Mid'
        ELSE 'High'
    END AS price_category

FROM restaurants

ORDER BY price_category, normalized_rating DESC;
"""
mycursor.execute(query)
out = mycursor.fetchall()
print(tabulate(out[:20], headers=[i[0] for i in mycursor.description], tablefmt='psql'))

+----------------------------------------+-----------------------+---------------------+------------------+
| name                                   | location              |   normalized_rating | price_category   |
|----------------------------------------+-----------------------+---------------------+------------------|
| byg brewski brewing company            | sarjapur road         |             4.86526 | High             |
| ab's - absolute barbecues              | btm                   |             4.81553 | High             |
| ab's - absolute barbecues              | marathahalli          |             4.75836 | High             |
| the black pearl                        | marathahalli          |             4.73048 | High             |
| chili's american grill & bar           | malleshwaram          |             4.72464 | High             |
| flechazo                               | whitefield            |             4.72362 | High             |
| the boozy griffin                      | marathahalli          |             4.69988 | High             |
| asia kitchen by mainland china         | koramangala 5th block |             4.6875  | High             |
| the globe grub                         | marathahalli          |             4.68297 | High             |
| toit                                   | indiranagar           |             4.66976 | High             |
| punjab grill                           | malleshwaram          |             4.66752 | High             |
| the black pearl                        | koramangala 5th block |             4.65727 | High             |
| big pitcher                            | old airport road      |             4.65108 | High             |
| ab's - absolute barbecues              | whitefield            |             4.64759 | High             |
| flechazo                               | marathahalli          |             4.63929 | High             |
| barbeque nation                        | indiranagar           |             4.63927 | High             |
| biergarten                             | whitefield            |             4.63694 | High             |
| brew and barbeque - a microbrewery pub | marathahalli          |             4.6258  | High             |
| chianti                                | koramangala 5th block |             4.6135  | High             |
| hammered                               | cunningham road       |             4.61009 | High             |
+----------------------------------------+-----------------------+---------------------+------------------+