In [1]:
# installation of pandas, numpy and matplotlib
%pip install pandas
%pip install numpy

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.4.4)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

In [3]:
file_path = "/workspaces/MiniProject1_GUVI/Uber_Eats_data.csv"
df = pd.read_csv(file_path)

In [4]:
df.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [33]:
df.shape

(23046, 13)

In [30]:
df.name.duplicated().any()

np.True_

In [31]:
df.name.duplicated().sum()

np.int64(19904)

In [35]:
df.name.value_counts()

name
Onesta               85
Empire Restaurant    67
KFC                  59
McDonald's           57
Pizza Hut            56
                     ..
Hunan Express         1
Bao & Grills          1
Gongura               1
Tuk-Tuk               1
Fujian Express        1
Name: count, Length: 3142, dtype: int64

In [42]:
df['name'] = df['name'].str.lower().str.strip()

In [43]:
df.name.value_counts()

name
onesta               85
empire restaurant    67
kfc                  59
mcdonald's           57
pizza hut            56
                     ..
hunan express         1
bao & grills          1
gongura               1
tuk-tuk               1
fujian express        1
Name: count, Length: 3135, dtype: int64

In [44]:
df.online_order.value_counts()

online_order
Yes    16297
No      6749
Name: count, dtype: int64

In [39]:
df.book_table.value_counts()

book_table
No     17005
Yes     6041
Name: count, dtype: int64

In [40]:
df.rate.value_counts()

rate
3.9/5     1689
3.9 /5    1549
4.0/5     1469
4.1/5     1398
4.0 /5    1391
          ...
2.2 /5       7
2.0 /5       7
2.0/5        4
1.8 /5       3
1.8/5        2
Name: count, Length: 62, dtype: int64

In [41]:
df.rate.unique()

<StringArray>
[ '4.1/5',  '3.8/5',  '3.7/5',  '4.6/5',  '4.0/5',  '4.2/5',  '3.9/5',
  '3.0/5',  '3.6/5',  '2.8/5',  '4.4/5',  '3.1/5',  '4.3/5',  '2.6/5',
  '3.3/5',  '3.5/5', '3.8 /5',  '3.2/5',  '4.5/5',  '2.5/5',  '2.9/5',
  '3.4/5',  '2.7/5',  '4.7/5',  '2.4/5',  '2.2/5',  '2.3/5',  '4.8/5',
 '3.9 /5', '4.2 /5', '4.0 /5', '4.1 /5', '2.9 /5', '2.7 /5', '2.5 /5',
 '2.6 /5', '4.5 /5', '4.3 /5', '3.7 /5', '4.4 /5',  '4.9/5',  '2.1/5',
  '2.0/5',  '1.8/5', '3.4 /5', '3.6 /5', '3.3 /5', '4.6 /5', '4.9 /5',
 '3.2 /5', '3.0 /5', '2.8 /5', '3.5 /5', '3.1 /5', '4.8 /5', '2.3 /5',
 '4.7 /5', '2.4 /5', '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5']
Length: 62, dtype: str

In [45]:
df['rate'] = df.rate.str.replace('/5','')

In [46]:
df.rate

0         4.1
1         4.1
2         3.8
3         3.7
4         3.8
         ...
23188    3.8
23189    3.9
23190    2.8
23191    2.5
23192    4.3
Name: rate, Length: 23046, dtype: str

In [47]:
df['rate']=df.rate.astype(float)

In [48]:
df.rate

0        4.1
1        4.1
2        3.8
3        3.7
4        3.8
        ...
23188    3.8
23189    3.9
23190    2.8
23191    2.5
23192    4.3
Name: rate, Length: 23046, dtype: float64

In [49]:
df.describe()

               rate         votes
count  23046.000000  23046.000000
mean       3.904383    604.908444
std        0.426365   1117.367014
min        1.800000      0.000000
25%        3.800000    103.000000
50%        4.000000    224.000000
75%        4.200000    591.000000
max        4.900000  16832.000000

In [50]:
df.rate.isnull().sum()

np.int64(0)